### ISSUE TITLE
Добавление счетчика cloud + HA 

### ISSUE THREAD

**Issue by Keks1975** [lizardsystems/hass-taipit#3]
Добрый день!
Добавил счетчик в приложение все отлично, настроил тарифы, добавил интеграцию в Home Assistant, но не добавились сенсоры Активная энергия T2 и Активная энергия T3 и не добавляются. на Активная энергия T1 даже уже считает потребление.
Правильно понимаю и надеюсь, сенсоры появятся когда по тарифам Т2 и Т3 будет потребление? или моя догадка не верна? Как понять и добавить сенсорам  Т2 и Т3?
Спасибо.

**Comment by vzagorovskiy** [comment]
из облака приходит информация на сколько тарифов наcтроен счетчик, и только эти сенсоры с тарифами будут отображаться. по остальным просто не приходят сведения.

**Comment by vzagorovskiy** [comment]
Установите правильный тариф в облаке
![image](https://github.com/lizardsystems/hass-taipit/assets/4923679/17049543-1e1c-455a-9a61-9965bf7c9fde)

**Comment by Keks1975** [comment]
При добовлении сразу установил.
![image](https://github.com/lizardsystems/hass-taipit/assets/118057894/95fb5e54-7176-469f-83ff-f46d791c663f)

**Comment by vzagorovskiy** [comment]
В вашем случае как и моем будет приходить только T1 и T2. Сейчас T2 тоже создан но он скрыт и будет скрытым пока не придут значения T2.

**Comment by Keks1975** [comment]
Так я и предполагал. Спасибо. Крутая интеграция и самое главное из коробки.  Осталось из услуг добавить учет GAZа. Удачи.

**Comment by vzagorovskiy** [comment]
Сейчас делаю интеграцию с мой газ смородина, думаю через месяцок будет готово.
https://мойгаз.смородина.онлайн/

**Comment by vzagorovskiy** [comment]
Первуя часть сделал апи разобрал https://github.com/lizardsystems/aiomygas
Сейчас пишу интеграцию будет здесь https://github.com/lizardsystems/hass-mygas

**Comment by Keks1975** [comment]
мой газ смородина - можно поподробнее о сервисе, система биониг? или учет с устройств? где можно почитать про сервис?

**Comment by vzagorovskiy** [comment]
Это прием показаний за услуги и биллинг.
т.е. HA будет туда отправлять туда показания раз в месяц.
Учет (съем показаний) реализовал сам на на ватериусе, т.е данные поступают в HA а потом раз в месяц отправляются в смородину.

**Comment by vzagorovskiy** [comment]
С электричеством тоже так же делается, если у вас ТНС энерго то можно на автомате отправлять показания через вот эту интеграцию https://github.com/lizardsystems/hass-tnse

**Comment by Keks1975** [comment]
У на в Крыму все сложно. в  крымэнерго, крым вода и крымтеплоэнерго нет даже мэйла для отправки показаний, только передовать можно по телефону и в ЛК поставщика услуг.
ватериусе у меня нет, учет в НА ведет счетчики Елихант СВТ-15 (горячая) и СВД-15 (холодная)

**Comment by vzagorovskiy** [comment]
ватериус он только так называется им не только воду мерять можно, вода у нас тоже вручную подается т.к. муниципальный поставщик.
я его к счетчику газа прикрутил и настроил интеграцию через mqtt 
![image](https://github.com/lizardsystems/hass-taipit/assets/4923679/81afbadb-7c1a-4d4e-b998-1393d8661102)

**Comment by Keks1975** [comment]
В моем случаи еще нет счетчика газа и буду устанавливать и остановился на изящном варианте счётчика. Счетчик газа СГБД-*.* 
https://elehant.ru/productpage/SGBD/1.6

**Comment by Keks1975** [comment]
Вопрос можно закрывать. Показания появились в счетчике и сенсор Т2 появился в НА. Проверено.
