### ISSUE TITLE
Интервал обновления с 30 минут на 10 минут

### ISSUE THREAD

**Issue by Keks1975** [lizardsystems/hass-taipit#4]
Добрый день!
Большая просьба, изменить интервал обновления сенсоров с 30 минут на 10 минут, а лучше если будет возможность самому в НА выставлять требуемый интервал обновления сенсоров.
Переписывался с технической службой Тапит и они подтвердили изменения обновления на 10 минут.
От себя хочу сказать, спасибо за вашу проделанную работу. крутая интеграция.

**Comment by Keks1975** [comment]
или скажите точно где менять в файлах интервал.

**Comment by vzagorovskiy** [comment]
в принципе не проблема, только не быстро. А на каких счетчиках 10 минут?

**Comment by Keks1975** [comment]
У меня НЕВА МТ 114 AS WF1P 5(60)A

**Comment by vzagorovskiy** [comment]
У меня такой же, НЕВА МТ 114 AS WF1P 5(60)A

Он раз в полчаса показания отправляет в 0 минут и в 30 минут  плюс минус ошибка локальных часов в счетчике

**Comment by vzagorovskiy** [comment]
Добавил в новом релизе возможность измения интервала обновления

**Comment by Keks1975** [comment]
Добрый вечер!
Установил релиз 1.4.0.
Выпала ошибка, Интеграция не запускается. 

Logger: custom_components.taipit
Source: helpers/update_coordinator.py:313
Integration: Тайпит ([documentation](https://github.com/lizardsystems/hass-taipit), [issues](https://github.com/lizardsystems/hass-taipit/issues))
First occurred: 22:03:08 (3 occurrences)
Last logged: 22:03:24

Unexpected error fetching taipit data: '<' not supported between instances of 'range' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/taipit/coordinator.py", line 126, in _async_update_data
    self.update_interval = get_update_interval(self.update_period)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/taipit/helpers.py", line 49, in get_update_interval
    next_time = dt.find_next_time_expression_time(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 414, in find_next_time_expression_time
    next_hour = _lower_bound(hours, result.hour)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 362, in _lower_bound
    if (left := bisect.bisect_left(arr, cmp)) == len(arr):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'range' and 'int'

**Comment by vzagorovskiy** [comment]
Да, уже поправил. Сейчас залью.

**Comment by Keks1975** [comment]
отлично. Спасибо

**Comment by Keks1975** [comment]
Добрый день!
После обновления появилось ошибка, а так все работает
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:288
First occurred: 10:00:15 (1 occurrences)
Last logged: 10:00:15

Validation of translation placeholders for localized (ru) string component.homeassistant.issues.config_entry_reauth.title failed

**Comment by vzagorovskiy** [comment]
Да похоже в новом HA что то поломали
https://github.com/home-assistant/core/issues/111516
